from __userdirs import *

( USER_DIR_DESKTOP,
  USER_DIR_DOCUMENTS,
  USER_DIR_DOWNLOAD,
  USER_DIR_MUSIC,
  USER_DIR_PICTURES,
  USER_DIR_PUBLIC_SHARE,
  USER_DIR_TEMPLATES,
  USER_DIR_VIDEOS
) = range(8)
